/**
 * This class is generated by jOOQ
 */
package com.gemtastic.carshop.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Car extends org.jooq.impl.TableImpl<com.gemtastic.carshop.tables.records.CarRecord> {

	private static final long serialVersionUID = 2117412830;

	/**
	 * The reference instance of <code>public.car</code>
	 */
	public static final com.gemtastic.carshop.tables.Car CAR = new com.gemtastic.carshop.tables.Car();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.gemtastic.carshop.tables.records.CarRecord> getRecordType() {
		return com.gemtastic.carshop.tables.records.CarRecord.class;
	}

	/**
	 * The column <code>public.car.id</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CarRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.car.license_plate</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CarRecord, java.lang.String> LICENSE_PLATE = createField("license_plate", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.car.odometer</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CarRecord, java.lang.Long> ODOMETER = createField("odometer", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.car.car_model</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CarRecord, java.lang.Integer> CAR_MODEL = createField("car_model", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.car</code> table reference
	 */
	public Car() {
		this("car", null);
	}

	/**
	 * Create an aliased <code>public.car</code> table reference
	 */
	public Car(java.lang.String alias) {
		this(alias, com.gemtastic.carshop.tables.Car.CAR);
	}

	private Car(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.tables.records.CarRecord> aliased) {
		this(alias, aliased, null);
	}

	private Car(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.tables.records.CarRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.gemtastic.carshop.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.gemtastic.carshop.tables.records.CarRecord, java.lang.Integer> getIdentity() {
		return com.gemtastic.carshop.Keys.IDENTITY_CAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.CarRecord> getPrimaryKey() {
		return com.gemtastic.carshop.Keys.CAR_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.CarRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.CarRecord>>asList(com.gemtastic.carshop.Keys.CAR_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.gemtastic.carshop.tables.records.CarRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.gemtastic.carshop.tables.records.CarRecord, ?>>asList(com.gemtastic.carshop.Keys.CAR__CAR_CAR_MODEL_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.gemtastic.carshop.tables.Car as(java.lang.String alias) {
		return new com.gemtastic.carshop.tables.Car(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.gemtastic.carshop.tables.Car rename(java.lang.String name) {
		return new com.gemtastic.carshop.tables.Car(name, null);
	}
}
