/**
 * This class is generated by jOOQ
 */
package com.gemtastic.carshop.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarModel extends org.jooq.impl.TableImpl<com.gemtastic.carshop.tables.records.CarModelRecord> {

	private static final long serialVersionUID = -381793982;

	/**
	 * The reference instance of <code>public.car_model</code>
	 */
	public static final com.gemtastic.carshop.tables.CarModel CAR_MODEL = new com.gemtastic.carshop.tables.CarModel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.gemtastic.carshop.tables.records.CarModelRecord> getRecordType() {
		return com.gemtastic.carshop.tables.records.CarModelRecord.class;
	}

	/**
	 * The column <code>public.car_model.id</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CarModelRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.car_model.fuel_type</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CarModelRecord, java.lang.String> FUEL_TYPE = createField("fuel_type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.car_model.model_year</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CarModelRecord, java.lang.Integer> MODEL_YEAR = createField("model_year", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.car_model.model</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CarModelRecord, java.lang.String> MODEL = createField("model", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.car_model.make</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CarModelRecord, java.lang.Integer> MAKE = createField("make", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.car_model</code> table reference
	 */
	public CarModel() {
		this("car_model", null);
	}

	/**
	 * Create an aliased <code>public.car_model</code> table reference
	 */
	public CarModel(java.lang.String alias) {
		this(alias, com.gemtastic.carshop.tables.CarModel.CAR_MODEL);
	}

	private CarModel(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.tables.records.CarModelRecord> aliased) {
		this(alias, aliased, null);
	}

	private CarModel(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.tables.records.CarModelRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.gemtastic.carshop.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.gemtastic.carshop.tables.records.CarModelRecord, java.lang.Integer> getIdentity() {
		return com.gemtastic.carshop.Keys.IDENTITY_CAR_MODEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.CarModelRecord> getPrimaryKey() {
		return com.gemtastic.carshop.Keys.CAR_MODEL_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.CarModelRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.CarModelRecord>>asList(com.gemtastic.carshop.Keys.CAR_MODEL_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.gemtastic.carshop.tables.records.CarModelRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.gemtastic.carshop.tables.records.CarModelRecord, ?>>asList(com.gemtastic.carshop.Keys.CAR_MODEL__CAR_MODEL_MAKE_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.gemtastic.carshop.tables.CarModel as(java.lang.String alias) {
		return new com.gemtastic.carshop.tables.CarModel(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.gemtastic.carshop.tables.CarModel rename(java.lang.String name) {
		return new com.gemtastic.carshop.tables.CarModel(name, null);
	}
}
