/**
 * This class is generated by jOOQ
 */
package com.gemtastic.carshop.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Certification extends org.jooq.impl.TableImpl<com.gemtastic.carshop.tables.records.CertificationRecord> {

	private static final long serialVersionUID = 859056214;

	/**
	 * The reference instance of <code>public.certification</code>
	 */
	public static final com.gemtastic.carshop.tables.Certification CERTIFICATION = new com.gemtastic.carshop.tables.Certification();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.gemtastic.carshop.tables.records.CertificationRecord> getRecordType() {
		return com.gemtastic.carshop.tables.records.CertificationRecord.class;
	}

	/**
	 * The column <code>public.certification.employee</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CertificationRecord, java.lang.Integer> EMPLOYEE = createField("employee", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.certification.make</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.CertificationRecord, java.lang.Integer> MAKE = createField("make", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.certification</code> table reference
	 */
	public Certification() {
		this("certification", null);
	}

	/**
	 * Create an aliased <code>public.certification</code> table reference
	 */
	public Certification(java.lang.String alias) {
		this(alias, com.gemtastic.carshop.tables.Certification.CERTIFICATION);
	}

	private Certification(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.tables.records.CertificationRecord> aliased) {
		this(alias, aliased, null);
	}

	private Certification(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.tables.records.CertificationRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.gemtastic.carshop.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.CertificationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.CertificationRecord>>asList(com.gemtastic.carshop.Keys.CERTIFICATION_EMPLOYEE_MAKE_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.gemtastic.carshop.tables.records.CertificationRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.gemtastic.carshop.tables.records.CertificationRecord, ?>>asList(com.gemtastic.carshop.Keys.CERTIFICATION__CERTIFICATION_EMPLOYEE_FKEY, com.gemtastic.carshop.Keys.CERTIFICATION__CERTIFICATION_MAKE_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.gemtastic.carshop.tables.Certification as(java.lang.String alias) {
		return new com.gemtastic.carshop.tables.Certification(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.gemtastic.carshop.tables.Certification rename(java.lang.String name) {
		return new com.gemtastic.carshop.tables.Certification(name, null);
	}
}
