/**
 * This class is generated by jOOQ
 */
package com.gemtastic.carshop.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MalfunctionReports extends org.jooq.impl.TableImpl<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord> {

	private static final long serialVersionUID = -443495547;

	/**
	 * The reference instance of <code>public.malfunction_reports</code>
	 */
	public static final com.gemtastic.carshop.tables.MalfunctionReports MALFUNCTION_REPORTS = new com.gemtastic.carshop.tables.MalfunctionReports();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord> getRecordType() {
		return com.gemtastic.carshop.tables.records.MalfunctionReportsRecord.class;
	}

	/**
	 * The column <code>public.malfunction_reports.id</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.malfunction_reports.message</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord, java.lang.String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.malfunction_reports.report_date</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord, java.sql.Date> REPORT_DATE = createField("report_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>public.malfunction_reports.car</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord, java.lang.Integer> CAR = createField("car", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.malfunction_reports</code> table reference
	 */
	public MalfunctionReports() {
		this("malfunction_reports", null);
	}

	/**
	 * Create an aliased <code>public.malfunction_reports</code> table reference
	 */
	public MalfunctionReports(java.lang.String alias) {
		this(alias, com.gemtastic.carshop.tables.MalfunctionReports.MALFUNCTION_REPORTS);
	}

	private MalfunctionReports(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord> aliased) {
		this(alias, aliased, null);
	}

	private MalfunctionReports(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.gemtastic.carshop.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord, java.lang.Integer> getIdentity() {
		return com.gemtastic.carshop.Keys.IDENTITY_MALFUNCTION_REPORTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord> getPrimaryKey() {
		return com.gemtastic.carshop.Keys.MALFUNCTION_REPORTS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord>>asList(com.gemtastic.carshop.Keys.MALFUNCTION_REPORTS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.gemtastic.carshop.tables.records.MalfunctionReportsRecord, ?>>asList(com.gemtastic.carshop.Keys.MALFUNCTION_REPORTS__MALFUNCTION_REPORTS_CAR_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.gemtastic.carshop.tables.MalfunctionReports as(java.lang.String alias) {
		return new com.gemtastic.carshop.tables.MalfunctionReports(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.gemtastic.carshop.tables.MalfunctionReports rename(java.lang.String name) {
		return new com.gemtastic.carshop.tables.MalfunctionReports(name, null);
	}
}
