/**
 * This class is generated by jOOQ
 */
package com.gemtastic.carshop.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarModelRecord extends org.jooq.impl.UpdatableRecordImpl<com.gemtastic.carshop.tables.records.CarModelRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 203132009;

	/**
	 * Setter for <code>public.car_model.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.car_model.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.car_model.fuel_type</code>.
	 */
	public void setFuelType(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.car_model.fuel_type</code>.
	 */
	public java.lang.String getFuelType() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.car_model.model_year</code>.
	 */
	public void setModelYear(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.car_model.model_year</code>.
	 */
	public java.lang.Integer getModelYear() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.car_model.model</code>.
	 */
	public void setModel(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.car_model.model</code>.
	 */
	public java.lang.String getModel() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.car_model.make</code>.
	 */
	public void setMake(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.car_model.make</code>.
	 */
	public java.lang.Integer getMake() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.gemtastic.carshop.tables.CarModel.CAR_MODEL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.gemtastic.carshop.tables.CarModel.CAR_MODEL.FUEL_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.gemtastic.carshop.tables.CarModel.CAR_MODEL.MODEL_YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.gemtastic.carshop.tables.CarModel.CAR_MODEL.MODEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.gemtastic.carshop.tables.CarModel.CAR_MODEL.MAKE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFuelType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getModelYear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getModel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getMake();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarModelRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarModelRecord value2(java.lang.String value) {
		setFuelType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarModelRecord value3(java.lang.Integer value) {
		setModelYear(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarModelRecord value4(java.lang.String value) {
		setModel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarModelRecord value5(java.lang.Integer value) {
		setMake(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CarModelRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.String value4, java.lang.Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CarModelRecord
	 */
	public CarModelRecord() {
		super(com.gemtastic.carshop.tables.CarModel.CAR_MODEL);
	}

	/**
	 * Create a detached, initialised CarModelRecord
	 */
	public CarModelRecord(java.lang.Integer id, java.lang.String fuelType, java.lang.Integer modelYear, java.lang.String model, java.lang.Integer make) {
		super(com.gemtastic.carshop.tables.CarModel.CAR_MODEL);

		setValue(0, id);
		setValue(1, fuelType);
		setValue(2, modelYear);
		setValue(3, model);
		setValue(4, make);
	}
}
