/**
 * This class is generated by jOOQ
 */
package com.gemtastic.carshop.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OwnershipRecord extends org.jooq.impl.TableRecordImpl<com.gemtastic.carshop.tables.records.OwnershipRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1746712717;

	/**
	 * Setter for <code>public.ownership.owner</code>.
	 */
	public void setOwner(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.ownership.owner</code>.
	 */
	public java.lang.Integer getOwner() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.ownership.car</code>.
	 */
	public void setCar(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.ownership.car</code>.
	 */
	public java.lang.Integer getCar() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.gemtastic.carshop.tables.Ownership.OWNERSHIP.OWNER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.gemtastic.carshop.tables.Ownership.OWNERSHIP.CAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getOwner();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getCar();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OwnershipRecord value1(java.lang.Integer value) {
		setOwner(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OwnershipRecord value2(java.lang.Integer value) {
		setCar(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OwnershipRecord values(java.lang.Integer value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OwnershipRecord
	 */
	public OwnershipRecord() {
		super(com.gemtastic.carshop.tables.Ownership.OWNERSHIP);
	}

	/**
	 * Create a detached, initialised OwnershipRecord
	 */
	public OwnershipRecord(java.lang.Integer owner, java.lang.Integer car) {
		super(com.gemtastic.carshop.tables.Ownership.OWNERSHIP);

		setValue(0, owner);
		setValue(1, car);
	}
}
