/**
 * This class is generated by jOOQ
 */
package com.gemtastic.carshop.db;

/**
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.address
	 */
	public static final com.gemtastic.carshop.db.tables.Address ADDRESS = com.gemtastic.carshop.db.tables.Address.ADDRESS;

	/**
	 * The table public.appointments
	 */
	public static final com.gemtastic.carshop.db.tables.Appointments APPOINTMENTS = com.gemtastic.carshop.db.tables.Appointments.APPOINTMENTS;

	/**
	 * The table public.car
	 */
	public static final com.gemtastic.carshop.db.tables.Car CAR = com.gemtastic.carshop.db.tables.Car.CAR;

	/**
	 * The table public.car_model
	 */
	public static final com.gemtastic.carshop.db.tables.CarModel CAR_MODEL = com.gemtastic.carshop.db.tables.CarModel.CAR_MODEL;

	/**
	 * The table public.certification
	 */
	public static final com.gemtastic.carshop.db.tables.Certification CERTIFICATION = com.gemtastic.carshop.db.tables.Certification.CERTIFICATION;

	/**
	 * The table public.customer
	 */
	public static final com.gemtastic.carshop.db.tables.Customer CUSTOMER = com.gemtastic.carshop.db.tables.Customer.CUSTOMER;

	/**
	 * The table public.employees
	 */
	public static final com.gemtastic.carshop.db.tables.Employees EMPLOYEES = com.gemtastic.carshop.db.tables.Employees.EMPLOYEES;

	/**
	 * The table public.make
	 */
	public static final com.gemtastic.carshop.db.tables.Make MAKE = com.gemtastic.carshop.db.tables.Make.MAKE;

	/**
	 * The table public.malfunction_reports
	 */
	public static final com.gemtastic.carshop.db.tables.MalfunctionReports MALFUNCTION_REPORTS = com.gemtastic.carshop.db.tables.MalfunctionReports.MALFUNCTION_REPORTS;

	/**
	 * The table public.ownership
	 */
	public static final com.gemtastic.carshop.db.tables.Ownership OWNERSHIP = com.gemtastic.carshop.db.tables.Ownership.OWNERSHIP;
}
