/**
 * This class is generated by jOOQ
 */
package com.gemtastic.carshop.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer extends org.jooq.impl.TableImpl<com.gemtastic.carshop.db.tables.records.CustomerRecord> {

	private static final long serialVersionUID = -942880351;

	/**
	 * The reference instance of <code>public.customer</code>
	 */
	public static final com.gemtastic.carshop.db.tables.Customer CUSTOMER = new com.gemtastic.carshop.db.tables.Customer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.gemtastic.carshop.db.tables.records.CustomerRecord> getRecordType() {
		return com.gemtastic.carshop.db.tables.records.CustomerRecord.class;
	}

	/**
	 * The column <code>public.customer.id</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.db.tables.records.CustomerRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.customer.first_name</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.db.tables.records.CustomerRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.customer.last_name</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.db.tables.records.CustomerRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.customer.date_of_birth</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.db.tables.records.CustomerRecord, java.sql.Date> DATE_OF_BIRTH = createField("date_of_birth", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>public.customer.gender</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.db.tables.records.CustomerRecord, java.lang.String> GENDER = createField("gender", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.customer.phone</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.db.tables.records.CustomerRecord, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.customer.email</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.db.tables.records.CustomerRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.customer.address</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.db.tables.records.CustomerRecord, java.lang.Integer> ADDRESS = createField("address", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.customer</code> table reference
	 */
	public Customer() {
		this("customer", null);
	}

	/**
	 * Create an aliased <code>public.customer</code> table reference
	 */
	public Customer(java.lang.String alias) {
		this(alias, com.gemtastic.carshop.db.tables.Customer.CUSTOMER);
	}

	private Customer(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.db.tables.records.CustomerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Customer(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.db.tables.records.CustomerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.gemtastic.carshop.db.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.gemtastic.carshop.db.tables.records.CustomerRecord, java.lang.Integer> getIdentity() {
		return com.gemtastic.carshop.db.Keys.IDENTITY_CUSTOMER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.gemtastic.carshop.db.tables.records.CustomerRecord> getPrimaryKey() {
		return com.gemtastic.carshop.db.Keys.CUSTOMER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.gemtastic.carshop.db.tables.records.CustomerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.gemtastic.carshop.db.tables.records.CustomerRecord>>asList(com.gemtastic.carshop.db.Keys.CUSTOMER_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.gemtastic.carshop.db.tables.records.CustomerRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.gemtastic.carshop.db.tables.records.CustomerRecord, ?>>asList(com.gemtastic.carshop.db.Keys.CUSTOMER__CUSTOMER_ADDRESS_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.gemtastic.carshop.db.tables.Customer as(java.lang.String alias) {
		return new com.gemtastic.carshop.db.tables.Customer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.gemtastic.carshop.db.tables.Customer rename(java.lang.String name) {
		return new com.gemtastic.carshop.db.tables.Customer(name, null);
	}
}
