/**
 * This class is generated by jOOQ
 */
package com.gemtastic.carshop.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Make extends org.jooq.impl.TableImpl<com.gemtastic.carshop.db.tables.records.MakeRecord> {

	private static final long serialVersionUID = 1658102591;

	/**
	 * The reference instance of <code>public.make</code>
	 */
	public static final com.gemtastic.carshop.db.tables.Make MAKE = new com.gemtastic.carshop.db.tables.Make();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.gemtastic.carshop.db.tables.records.MakeRecord> getRecordType() {
		return com.gemtastic.carshop.db.tables.records.MakeRecord.class;
	}

	/**
	 * The column <code>public.make.id</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.db.tables.records.MakeRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.make.make</code>.
	 */
	public final org.jooq.TableField<com.gemtastic.carshop.db.tables.records.MakeRecord, java.lang.String> MAKE_ = createField("make", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>public.make</code> table reference
	 */
	public Make() {
		this("make", null);
	}

	/**
	 * Create an aliased <code>public.make</code> table reference
	 */
	public Make(java.lang.String alias) {
		this(alias, com.gemtastic.carshop.db.tables.Make.MAKE);
	}

	private Make(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.db.tables.records.MakeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Make(java.lang.String alias, org.jooq.Table<com.gemtastic.carshop.db.tables.records.MakeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.gemtastic.carshop.db.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.gemtastic.carshop.db.tables.records.MakeRecord, java.lang.Integer> getIdentity() {
		return com.gemtastic.carshop.db.Keys.IDENTITY_MAKE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.gemtastic.carshop.db.tables.records.MakeRecord> getPrimaryKey() {
		return com.gemtastic.carshop.db.Keys.MAKE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.gemtastic.carshop.db.tables.records.MakeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.gemtastic.carshop.db.tables.records.MakeRecord>>asList(com.gemtastic.carshop.db.Keys.MAKE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.gemtastic.carshop.db.tables.Make as(java.lang.String alias) {
		return new com.gemtastic.carshop.db.tables.Make(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.gemtastic.carshop.db.tables.Make rename(java.lang.String name) {
		return new com.gemtastic.carshop.db.tables.Make(name, null);
	}
}
